### ISSUE TITLE
ガイドラインが欲しい

### ISSUE THREAD

**Issue by KOBA789** [bo-nami/today.robonami.app#1]
README に PR のガイドラインがあるといいと思います!

**Comment by bo-nami** [comment]
今日書いてみますね！！コメントありがとうございます。

**Comment by bo-nami** [comment]
@KOBA789 書いてみました！ご確認ください。
https://github.com/bo-nami/today.robonami.app/blob/master/README.md

**Comment by KOBA789** [comment]
よさそう!
